version: "3"
services:
  pozos-website:
    container_name: frontend_student_list
    depends_on:
      - pozos-api
    ports:
      - 8080:80
    volumes:
      - ${PWD}/website:/var/www/html
    image: php:apache
    environment:
      - USERNAME=jean-luc
      - PASSWORD=2024
      
  pozos-api:
    container_name: backend_student_list
    ports:
      - 4000:5000
    volumes:
      - ${PWD}/simple_api/student_age.json:/data/student_age.json
    image: jlmpande/student_list:1.0.0 